apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: values.yaml

helmCharts:
- name: helloworld
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: helloworld
  version: 0.2.0
  repo: https://crowdsecurity.github.io/helm-charts